apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: addressbookdeployment
spec:
  replicas: 2
  template: 
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
      - name: address-container
        image: rdsharma971994/tcsapp:11
        ports:
        - containerPort: 8080
