apiVersion: v1
kind: Service
metadata:
  name: addressbook-lb
  labels:
    service: addressbook-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 31444
    targetPort: 8080
    protocol: TCP
  selector:
    app: addressbook
